### ISSUE TITLE
Stop custom node when stopping the dataflow

### ISSUE THREAD

**Issue by phil-opp** [dora-rs/dora#136]
Requested by @haixuanTao

**Comment by phil-opp** [comment]
@haixuanTao Could you give more details on this request?

**Comment by haixuanTao** [comment]
The problem is that some python program such as ROS python nodes are based on a forever loop. When starting them through dora we might want to stop them on `dora stop`.

**Comment by haixuanTao** [comment]
But after discussion, we chose to leave the closing of those forever loops to the user as we might not have enough information on how to stop the nodes.

**Comment by phil-opp** [comment]
With the new event stream design merged in #162, all nodes should listen for incoming events, even if they don't expect inputs. Nodes that don't do this will be killed as soon as #184 is merged.

**Comment by haixuanTao** [comment]
Closing as rhis is now implemented with grace duration
