### ISSUE TITLE
exec the command `dora upgrade`  exception

### ISSUE THREAD

**Issue by meua** [dora-rs/dora#206]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11570442/224251703-cf3b7eda-78e5-4659-9576-ede8ab97c324.png)

**To Reproduce**
1. Dora upgrade daemon: `dora upgrade` 
2. The error is as follows：
thread 'main' panicked at 'not yet implemented', binaries/cli/src/main.rs:148:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/11570442/224252177-f5c0f00d-3925-40dc-9172-cbf143d9e0de.png)

**Environments (please complete the following information):**
 - System info: 
 Linux jia 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Dora version：
 dora-cli 0.1.3

**Comment by meua** [comment]
dora dashboard
dora upgrade
dora logs 
dora metrics
dora stats

**Comment by meua** [comment]
The same problem exists with the following command：
`dora dashboard`
`dora upgrade`
`dora logs `
`dora metrics`
`dora stats`

**Comment by phil-opp** [comment]
Thanks a lot for reporting! These are all commands that we envisioned for future releases of dora (see #81). However, they are not designed or implemented right now. So I think that it's best to remove them for now. I'll prepare a PR.
