### ISSUE TITLE
The dora service is not started. An error is reported execute dora list

### ISSUE THREAD

**Issue by meua** [dora-rs/dora#250]
**Describe the bug**
The dora service is not started. An error is reported execute dora list

**To Reproduce**
1. dora list

**Screenshots or Video**
![QQ20230414-201905](https://user-images.githubusercontent.com/11570442/232043025-dee08127-1415-444d-a140-66d56ea56da9.png)

**Environments (please complete the following information):**
 - System info: `Linux jia 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Dora version : 0.2.2

**Comment by phil-opp** [comment]
Could you clarify what behavior you are expecting? Do you think that the coordinator and daemon should be started automatically on `dora list`? Or do mean that we should improve the error message to e.g. "no dora coordinator is running" instead of "Connection refused"?

**Comment by meua** [comment]
> Could you clarify what behavior you are expecting? Do you think that the coordinator and daemon should be started automatically on `dora list`? Or do mean that we should improve the error message to e.g. "no dora coordinator is running" instead of "Connection refused"?

No, I think that when dora is not started, execute the dora list command, it should not report an error, it should remind the prompt that dora is not started

**Comment by phil-opp** [comment]
Thanks for clarifying! I opened https://github.com/dora-rs/dora/pull/254 to fix this.

**Comment by haixuanTao** [comment]
I may be wrong, but is this issue more geared toward the way the error is reported rather than the actual content of the error @meua ?

**Comment by meua** [comment]
> I may be wrong, but is this issue more geared toward the way the error is reported rather than the actual content of the error @meua ?

The dora return should clearly explain the cause of the problem, and should not directly throw an exception
