### ISSUE TITLE
todo: dora provides Chinese documents

### ISSUE THREAD

**Issue by meua** [dora-rs/dora#262]
**Is your feature request related to a problem? Please describe.**
Dora currently only has English documents and no Chinese documents, which is not very friendly to Chinese domestic users

**Describe the solution you'd like**
Dora documents can be switched between Chinese and English

**Describe alternatives you've considered**
dora supports Chinese documents

**Comment by meua** [comment]
I have translated the English technical documentation of dora into the corresponding Chinese technical documentation. How should I deploy it to facilitate language switching?

**Comment by haixuanTao** [comment]
I'm working on making dora doc multi-lingual although this feature is not ready yet.

**Comment by meua** [comment]
> I'm working on making dora doc multi-lingual although this feature is not ready yet.

:+1: :+1: :+1:

**Comment by haixuanTao** [comment]
The new documentation website: dora.carsmos.ai now supports Chinese translation through crowdin.
