### ISSUE TITLE
Dataflow with no specified name shows unnamed

### ISSUE THREAD

**Issue by meua** [dora-rs/dora#266]
**Is your feature request related to a problem? Please describe.**
Dataflow with no specified name shows unnamed, as follows:
![image](https://user-images.githubusercontent.com/11570442/233956455-7e8aed3a-ad10-4af1-ac09-c8ba8e498d7f.png)
```
impl Display for DataflowId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(name) = &self.name {
            write!(f, "[{name}] {}", self.uuid)
        } else {
            write!(f, "[<unnamed>] {}", self.uuid)
        }
    }
}
```

**Describe the solution you'd like**
Is it possible for dataflow without a name to randomly generate a unique name for it.

**Comment by phil-opp** [comment]
Thanks for reporting! Could you clarify what kind of name we should generate? There is already the unique ID for each dataflow (shown after the `[<unnamed>]`).

**Comment by phil-opp** [comment]
I guess we could use a crate such as [`names`](https://docs.rs/names/latest/names/) to generate human-readable names that are easier to read than the UUIDs. Is this what you were thinking?

**Comment by meua** [comment]
> 
Yes, short names are easier to remember, and using a combination of letters and numbers can significantly shorten this unique identifier
