### ISSUE TITLE
Cannot exec dora or dora-cli command when install dora with conda on macOS

### ISSUE THREAD

**Issue by jinlong-hao** [dora-rs/dora#313]
**Describe the bug**
cannot exec dora or dora-cli command when install dora with conda on macOS

**To Reproduce**

1. create a new conda env :  conda create -n dora python=3.9
2. activate dora:  conda activate dora
3. install dora and dora-cli in conda env:  pip install dora dora-cli 
4. exec dora-cli or dora comman in terminal

**Expected behavior**

expect dora can successfully run.

**Comment by jinlong-hao** [comment]
It's my first time use rust. 
I installed rust and dora with cargo,  the problem solved.

**Comment by haixuanTao** [comment]
I might add the cli to pip so that people can install it directly without cargo. Have fun trying out Rust ☺️

**Comment by haixuanTao** [comment]
For future reference, [`dora-cli`](https://pypi.org/project/dora-cli/) on Pypi is not our project.
