### ISSUE TITLE
Raise error when dora python operator doesn't return dora status

### ISSUE THREAD

**Issue by Felixhuangsiling** [dora-rs/dora#373]
Sometimes I forgot to put operators `DoraStatus.CONTINUE` which will fail the code without let me knowing it.

**Expected behavior**
I would like to have a error being raised to let me know that my code failed.

**Environments (please complete the following information):**
 - System info: linux
 - Dora version: 0.2.6
 - Python version: 3.8.10

**Comment by haixuanTao** [comment]
It seems that i cannot reproduce this error.

I get the following error:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: operator object_detection/op raised an error
   2: error in Python module at /home/peter/Documents/work/dora/examples/python-operator-dataflow/object_detection.py
   3: on_event must have enum return value
   4: AttributeError: 'NoneType' object has no attribute 'value'

```
