### ISSUE TITLE
Add a CMake example

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora#374]
Adding a cmake example can help get started for C/C++ users for dora :)

**Comment by XxChang** [comment]
This [repo](https://github.com/XxChang/dora_cmake_example) should work.

**Comment by haixuanTao** [comment]
Thanks @Xxchang for the repo! 

Would it be possible to modify one of the existing example or create a new example as a PR so that other people can get inspired if they are facing the same difficulties. 

Thanks again!

**Comment by haixuanTao** [comment]
Closed by #381
