### ISSUE TITLE
supersede dora-cli as dora in dora-cli bin 

### ISSUE THREAD

**Issue by linyihai** [dora-rs/dora#376]
Hello,  I came from the install guide, I found it  use 'alias' to make dora-cli as dora after install.
May be can supersede dora-cli with dora in dora-cli bin :
https://github.com/dora-rs/dora/blob/main/binaries/cli/Cargo.toml#L12

```
[[bin]]
name = "dora"
path = "src/main.rs"
```

this is will be useful in windows  cmd.exe can not support alias

**Comment by haixuanTao** [comment]
Hello,

Indeed, that could be great. We currently have an issue with naming as the python package for `dora` needs also to be named `dora` , but there can only be one dora. 

I wonder if there is not a better way to deal with this issue. 

As a temporary solution, you can use `dora-cli` when doing your testing.

**Comment by linyihai** [comment]
Thank you for solving the problem.

**Comment by haixuanTao** [comment]
No worries!

**Comment by haixuanTao** [comment]
This will be available in the next release!
