### ISSUE TITLE
two questions: 1. how to set the destination for ego vehicle? 2. how to print the variable?

### ISSUE THREAD

**Issue by caixxuan** [dora-rs/dora#404]
1. how to set the destination for ego vehicle? 
I did not find the file to set  of destination carla ego vehicle. how to set it?
2. how to print the variable?
I want to monitor some variables when running simulation, but it seems did not work using 'print(xx)'. are there some other ways to realize?

**Comment by caixxuan** [comment]
![Screenshot from 2023-12-27 22-02-41](https://github.com/dora-rs/dora/assets/110223255/fe3f5de0-9f57-45dc-9df5-2ff45e802d08)
if set the NUM_WAYPOINTS_AHEAD from 120 to 145，something wrong happened, the ego vehicle cannot work properly, how to fix?

**Comment by caixxuan** [comment]
> In order to change the goal destination you should look at the carla_gps_op.py and change it there.
> 
> in order to print anything you should us: dora logs <DATAFLOW_ID>
> 
> To see it printing there.
> 
> check the flush=true option in print to see in real time

sorry, I am not clear: 'dora logs <DATAFLOW_ID>' should write to the python script? and where to find '<DATAFLOW_ID>' ? flush=true where to set?

**Comment by caixxuan** [comment]
> > In order to change the goal destination you should look at the carla_gps_op.py and change it there.
> > in order to print anything you should us: dora logs <DATAFLOW_ID>
> > To see it printing there.
> > check the flush=true option in print to see in real time
> 
> sorry, I am not clear: 'dora logs <DATAFLOW_ID>' should write to the python script? and where to find '<DATAFLOW_ID>' ? flush=true where to set?

is there any example code?

**Comment by haixuanTao** [comment]
> ![Screenshot from 2023-12-27 22-02-41](https://github.com/dora-rs/dora/assets/110223255/fe3f5de0-9f57-45dc-9df5-2ff45e802d08)
> 
> if set the NUM_WAYPOINTS_AHEAD from 120 to 145，something wrong happened, the ego vehicle cannot work properly, how to fix?

I wouldn't recommend changing the number of waypoint ahead. You should probably revert back.

However, if you really want to you should change make sure that every message using the waypoints are reshaping the data in the right shape with this newly updated number of waypoints.

**Comment by haixuanTao** [comment]
> > In order to change the goal destination you should look at the carla_gps_op.py and change it there.
> 
> > 
> 
> > in order to print anything you should us: dora logs <DATAFLOW_ID>
> 
> > 
> 
> > To see it printing there.
> 
> > 
> 
> > check the flush=true option in print to see in real time
> 
> 
> 
> sorry, I am not clear: 'dora logs <DATAFLOW_ID>' should write to the python script? and where to find '<DATAFLOW_ID>' ? flush=true where to set?

You should type this in your terminal:

```bash
Dora logs c95d118b-cded-4531-a0e4-cd85b7c3916c carla_gps_op
```

In your Python script make sure to use:

```
print("test", flush=True)
```

**Comment by caixxuan** [comment]
It seems only something wrong happen, the print can work?
"description should only be set when status_code is set to StatusCode.ERROR"

**Comment by caixxuan** [comment]
> > > In order to change the goal destination you should look at the carla_gps_op.py and change it there.
> > 
> > 
> > > 
> > 
> > 
> > > in order to print anything you should us: dora logs <DATAFLOW_ID>
> > 
> > 
> > > 
> > 
> > 
> > > To see it printing there.
> > 
> > 
> > > 
> > 
> > 
> > > check the flush=true option in print to see in real time
> > 
> > 
> > sorry, I am not clear: 'dora logs <DATAFLOW_ID>' should write to the python script? and where to find '<DATAFLOW_ID>' ? flush=true where to set?
> 
> You should type this in your terminal:
> 
> ```shell
> Dora logs c95d118b-cded-4531-a0e4-cd85b7c3916c carla_gps_op
> ```
> 
> In your Python script make sure to use:
> 
> ```python
> print("test", flush=True)
> ```

it seems only work when fail:
description should only be set when status_code is set to StatusCode.ERROR

**Comment by caixxuan** [comment]
> > > In order to change the goal destination you should look at the carla_gps_op.py and change it there.
> > 
> > 
> > > 
> > 
> > 
> > > in order to print anything you should us: dora logs <DATAFLOW_ID>
> > 
> > 
> > > 
> > 
> > 
> > > To see it printing there.
> > 
> > 
> > > 
> > 
> > 
> > > check the flush=true option in print to see in real time
> > 
> > 
> > sorry, I am not clear: 'dora logs <DATAFLOW_ID>' should write to the python script? and where to find '<DATAFLOW_ID>' ? flush=true where to set?
> 
> You should type this in your terminal:
> 
> ```shell
> Dora logs c95d118b-cded-4531-a0e4-cd85b7c3916c carla_gps_op
> ```
> 
> In your Python script make sure to use:
> 
> ```python
> print("test", flush=True)
> ```

And the print is not executed in real time

**Comment by haixuanTao** [comment]
So the print of logs is not in real time and you will have to open and close it to take into account the latest logs. We're working on a better logging system but as of now, this is how we do logging.

**Comment by haixuanTao** [comment]
You can now check the logs in the `out` folder.
