### ISSUE TITLE
upgrade not able to remove old version  after upgrade dora 0.3.1

### ISSUE THREAD

**Issue by bobd988** [dora-rs/dora#411]
**Describe the bug**
Dora upgrade from 0.2.4 to 0.3.1 samples not long worked.  The 0.3.1 env was a PC is ubuntu 22.04.2  with conda env with python 3.11.  
It turns out the old dora version was not removed.

Following the steps to install to conda env

cargo install dora-cli
cargo install dora-coordinator
cargo install dora-daemon

the message showed the old dora-rs 0.2.4 was replaced with 0.3.1 successfully.  

**To Reproduce**
dora new abc_project --lang python
dora start dataflow.yml --name first-dataflow

the error is 
Traceback (most recent call last):
  File "<string>", line 3, in <module>
AssertionError: Python dora-rs should be 0.2.4, but current version is 0.3.1. Please reinstall it with: `pip install dora-rs==0.2.4 --force`
Could not validate yaml: Dataflow could not be validated.: Something went wrong with Python dora-rs. Please reinstall it with: `pip install dora-rs==0.2.4 --force`

dora --version showed -.2.4 ,  then cargo uninstall dora-cli, it showed two version is system.

 dora-cli@0.2.4
 dora-cli@0.3.1

cargo uninstall dora-cli@0.2.4
cargo install dora-cli@0.3.1 --force

now run dora-cli
dora-cli: command not found

**Expected behavior**
cargo install should replace the old with new version completely. However the old dora component was not cleaned. 

**Environments (please complete the following information):**
pip show dora-rs
Name: dora-rs
Version: 0.3.1

**Comment by haixuanTao** [comment]
Sorry. `dora-cli` has been renamed `dora` for consistency. 

You can just use dora without adding the -cli at the end.
