### ISSUE TITLE
 Error when modifying dora-rs node

### ISSUE THREAD

**Issue by WindsAtr** [dora-rs/dora#427]
I wanted to add the distribution_location_op/obstacles data flow in carla_gps_op.py, so I modified the node id in the oasis_agent_planning.yaml file: carla_gps_op, but the carla_gps_op.py file did not obtain the distribution_location_op/obstacles data.
This is the part I modified：
  - id: carla_gps_op
    operator:
      python: ../../carla/carla_gps_op.py
      outputs:
        - gps_waypoints
      inputs:
        opendrive: oasis_agent/opendrive
        objective_waypoints: oasis_agent/objective_waypoints
        position: oasis_agent/position
        obstacles: obstacle_location_op/obstacles
![1 (2)](https://github.com/dora-rs/dora/assets/147231750/25fd333e-5508-4774-a18b-f3e534a123dc)

**Comment by WindsAtr** [comment]
can anyone help me

**Comment by haixuanTao** [comment]
The way you modified the dataflow seems right. Are you sure that there is obstacles in front?

**Comment by haixuanTao** [comment]
This has been solved in the discord
