### ISSUE TITLE
Python API automatic `__str__` derivation

### ISSUE THREAD

**Issue by EricLBuehler** [dora-rs/dora#544]
Hello all!

Currently, we define the `__str__` method for the `PyEvent` struct to output the Rust equivalent of the `dbg!` macro:
```rust
fn __str__(&self) -> PyResult<String> {
    Ok(format!("{:#?}", &self.event))
}
```

> Note: the `Node` struct appears to not have a `__str__` implementation?

This format may be confusing for non-Rust users. Therefore, we should provide a Python user-friendly `__str__` implementation to all exported items from the Python API (`PyEvent` and `Node`).

Perhaps we can create a derive macro to facilitate this application, which will recursively descend to emulate a Python-style class print. However, because there are a few exported items to apply this to, it may be more reasonable to hard-code the representation? I would appreciate your thoughts.

**Comment by haixuanTao** [comment]
So, I think what we're trying to do is very similar to this: https://github.com/huggingface/tokenizers/pull/1542

Where we want to display the element within each rust object in a way that is pythonic.

Note that we should implement __str__ and __repr__ :)
