### ISSUE TITLE
Send multiple outputs to the frontend

### ISSUE THREAD

**Issue by XiaoKuge** [dora-rs/dora#617]
**Is your feature request related to a problem? Please describe.**
We have a frontend. While a dora-flow is running, we hope to be able to show outputs data from the middle nodes. 

**Describe the solution you'd like**
Middle nodes can send data easily to the external environment. 

**Describe alternatives you've considered**
N/A

**Additional context**
Thank you and best regards,

from MAE team

**Comment by haixuanTao** [comment]
Could you clarify the meaning of showing output from the middle node ? 


What do you use to show output ?

**Comment by XiaoKuge** [comment]
![image](https://github.com/user-attachments/assets/a51b199c-039b-4c03-b4ff-c7c6924e377c)
Assuming the psudo YAML script above, there is a "middle-node", and somehow we want it output something to Web browser (frontend).

Hope it helps. 

Thank you.

**Comment by haixuanTao** [comment]
So, currently we do not provide any web browser based API ( javascript, ...) 

However we could help provide a REST API for retrieving logs from opentelemetry, if that works for you?

**Comment by haixuanTao** [comment]
Closing this as I think the problem should be mostly solved with dynamic node.
