### ISSUE TITLE
 failed to run dora-daemon

### ISSUE THREAD

**Issue by haixuanTao** [dora-rs/dora#628]
It seems that we have left couple of errors that can stops the daemon when not resolving.

It could be good to check on `?` within the daemon main loop and try to encapsulate errors so that they don't stop the daemon.

## Error 1: Getting a running dataflow within the daemon that is no longer existent

```
failed to run dora-daemon: no running dataflow with ID `0191545a-94f9-7a2f-9217-f1971efba4f8`
```

## Error 2: Getting a dynamic node through the non flexible API in a non dynamic settings.

```bash
failed to run dora-daemon: failed to get dynamic node config within given dataflow: node with ID `terminal-print` in 0191545a-e2eb-7588-954f-6a6d03ce8f53 is not dynamic
```

I'm having trouble creating simple example but I believe that if we replace `?` in daemon main loop with something else we can avoid those errors.

**Comment by phil-opp** [comment]
I opened a PR to handle the two errors properly in more cases: https://github.com/dora-rs/dora/pull/631

> I believe that if we replace `?` in daemon main loop with something else we can avoid those errors.

There is not much that we can do instead at the main loop level. We could only log the error of course, but this is often not the correct solution. For example, we should report the error back to the caller in many cases (e.g. on a `NodeConfig` message).
